// Code generated by goctl. DO NOT EDIT.
package types

type StatusResponse struct {
	Status  string `json:"status"`
	Message string `json:"message"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
